### ISSUE TITLE
JSF websocket

### ISSUE THREAD

**Issue by ritonglue** [fmarchioni/practical-enterprise-development#3]
In the project ee-jsf-websocket, nothing changes in the browser after clicking the button. In the log, the random number is printed but nothing on the screen.

**Comment by fmarchioni** [comment]
Hi,
which branch are you testing with ? the only active branches are jakartaee and bootable-jakartaee

**Comment by ritonglue** [comment]
I was testing master with wildfly 25.0.1Final.
It works with wildfly 27.0.1.Final on branch jakartaee.
